# Generated by Django 6.0.4 on 2026-04-10 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('spent_for', models.CharField(choices=[('SELF', 'For Self'), ('HOME', 'For Home'), ('WORK', 'For Work'), ('OTHER', 'For Other')], default='SELF', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('tobuy_for', models.CharField(choices=[('SELF', 'For Self'), ('HOME', 'For Home'), ('WORK', 'For Work'), ('OTHER', 'For Other')], default='SELF', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobuyitems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
