# Generated by Django 6.0.4 on 2026-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tobuyitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
