# Generated by Django 6.0.4 on 2026-04-27 14:45

import django.db.models.deletion
import tracker.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_spending_title_tobuyitem_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[tracker.validators.validate_positive_amount]),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spendings', to='tracker.category'),
        ),
        migrations.AlterField(
            model_name='tobuyitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tobuyitems', to='tracker.category'),
        ),
    ]
