# Generated by Django 6.0.4 on 2026-04-27 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_spending_amount_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_for', models.CharField(blank=True, choices=[('SELF', 'For Self'), ('HOME', 'For Home'), ('WORK', 'For Work'), ('OTHER', 'For Other')], max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tracker.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'category', 'spent_for', 'month', 'year'), name='unique_budget_per_category_spentfor_month_year'), models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('owner', 'spent_for', 'month', 'year'), name='unique_budget_per_spentfor_month_year_no_category'), models.UniqueConstraint(condition=models.Q(('spent_for__isnull', True)), fields=('owner', 'category', 'month', 'year'), name='unique_budget_per_category_month_year_no_spentfor'), models.UniqueConstraint(condition=models.Q(('category__isnull', True), ('spent_for__isnull', True)), fields=('owner', 'month', 'year'), name='unique_budget_per_month_year_no_category_no_spentfor')],
            },
        ),
    ]
