# Generated by Django 6.0.4 on 2026-04-28 12:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_category_spentfor_month_year',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_spentfor_month_year_no_category',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_category_month_year_no_spentfor',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_month_year_no_category_no_spentfor',
        ),
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('owner', 'category', 'spent_for', 'date'), name='unique_budget_per_category_spentfor_date'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('owner', 'spent_for', 'date'), name='unique_budget_per_spentfor_date_no_category'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('spent_for__isnull', True)), fields=('owner', 'category', 'date'), name='unique_budget_per_category_date_no_spentfor'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True), ('spent_for__isnull', True)), fields=('owner', 'date'), name='unique_budget_per_date_no_category_no_spentfor'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
    ]
