# Generated by Django 6.0.4 on 2026-04-28 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_budget_unique_budget_per_category_spentfor_month_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_category_spentfor_date',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_spentfor_date_no_category',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_category_date_no_spentfor',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_date_no_category_no_spentfor',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('owner', 'category', 'spent_for', 'month', 'year'), name='unique_budget_per_category_spentfor_month_year'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('owner', 'spent_for', 'month', 'year'), name='unique_budget_per_spentfor_month_year_no_category'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('spent_for__isnull', True)), fields=('owner', 'category', 'month', 'year'), name='unique_budget_per_category_month_year_no_spentfor'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True), ('spent_for__isnull', True)), fields=('owner', 'month', 'year'), name='unique_budget_per_month_year_no_category_no_spentfor'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='date',
        ),
    ]
