# Generated by Django 6.0.4 on 2026-05-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_budget_unique_budget_per_category_spentfor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='spent_for',
            field=models.CharField(blank=True, choices=[('HOME', 'For Home'), ('OTHER', 'For Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='spending',
            name='spent_for',
            field=models.CharField(choices=[('HOME', 'For Home'), ('OTHER', 'For Other')], default='HOME', max_length=10),
        ),
        migrations.AlterField(
            model_name='tobuyitem',
            name='tobuy_for',
            field=models.CharField(choices=[('HOME', 'For Home'), ('OTHER', 'For Other')], default='HOME', max_length=10),
        ),
    ]
