# Generated by Django 6.0.4 on 2026-05-01 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_budget_spent_for_alter_spending_spent_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_category_spentfor_month_year',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_spentfor_month_year_no_category',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_category_month_year_no_spentfor',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_month_year_no_category_no_spentfor',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='spent_for',
        ),
        migrations.RemoveField(
            model_name='tobuyitem',
            name='tobuy_for',
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('owner', 'category', 'month', 'year'), name='unique_budget_per_category_month_year'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('owner', 'month', 'year'), name='unique_budget_per_month_year_no_category'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='spent_for',
        ),
    ]
