# Generated by Django 6.0.4 on 2026-05-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_category_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='budget_amount',
        ),
    ]
