# Generated by Django 6.0.4 on 2026-05-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_amount_budget_budget_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='actual_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
